name: Continuous integration
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          username: stephanmisc
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.event_name == 'push'
      - uses: stepchowfun/toast/.github/actions/toast@master
        with:
          repo: stephanmisc/toast
          write_remote_cache: ${{ github.event_name == 'push' }}
      - uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      - uses: stepchowfun/toast/.github/actions/toast@master
        with:
          tasks: deploy
          repo: stephanmisc/toast
          write_remote_cache: ${{ github.event_name == 'push' }}
        env:
          DATABASE_INSTANCE_CONNECTION_NAME: gigamesh-296502:us-central1:gigamesh
          GAR_LOCATION: us-central1
          GCP_DEPLOY_CREDENTIALS: ${{ secrets.GCP_DEPLOY_CREDENTIALS }}
          GCP_PROJECT_ID: gigamesh-296502
          GCR_REGION: us-central1
          GCR_SERVICE_ACCOUNT: production@gigamesh-296502.iam.gserviceaccount.com
          STAGING_BUCKET: gigamesh-staging
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
